### ISSUE TITLE
 Argument 1 passed to Lord\Laroute\Routes\Collection::__construct() must be an instance of Illuminate\Routing\RouteCollection, array given

### ISSUE THREAD

**Issue by nyrik8989** [AXN-Informatique/laravel-laroute#7]
![image](https://user-images.githubusercontent.com/22983913/91463059-9a03d380-e893-11ea-82de-83ee5ef4b47d.png)

**Comment by nyrik8989** [comment]
![image](https://user-images.githubusercontent.com/22983913/91464587-675ada80-e895-11ea-8a80-2a4282a2fd2e.png)

**Comment by forxer** [comment]
This should be fix in 1.7.1, please upgrade
